FUNCTION-POOL ZTO_FGR_SAP04.                "MESSAGE-ID ..

* INCLUDE LZTO_FGR_SAP04D...                 " Local class definition

SELECTION-SCREEN BEGIN OF SCREEN 2025 TITLE TEXT-001.
  PARAMETERS : p_dist TYPE s_distance .
SELECTION-SCREEN END OF SCREEN 2025.

SELECTION-SCREEN BEGIN OF SCREEN 2026 TITLE TEXT-002.
  PARAMETERS : p_url TYPE s_url .
SELECTION-SCREEN END OF SCREEN 2026.

SELECTION-SCREEN BEGIN OF SCREEN 2027 TITLE TEXT-003.
  PARAMETERS : p_url_2 TYPE s_url .
SELECTION-SCREEN END OF SCREEN 2027.

SELECTION-SCREEN BEGIN OF SCREEN 2028 TITLE TEXT-004.
PARAMETERS: p_carrid TYPE s_carr_id,
            p_carrnm TYPE s_carrname,
            p_curr   TYPE s_currcode,
            p_url_3  TYPE s_carrurl.
SELECTION-SCREEN END OF SCREEN 2028.
